kumuluzee:
  name: recomender-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://192.168.2.195:2379
#  health:
#    checks:
#      etcd-health-check:
#        connection-url: http://etcd:2379/health
  metrics:
    web-instrumentation:
      - name: recomender-endpoint
        url-pattern: /v1/recomender/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="recomender">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="38afe0eb-8e75-40c2-9981-d4e281e01d18-ls.logit.io"
                                port="17217" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
configurations:
  neo4j:
    url: bolt://hobby-ghjnlebfkikggbkeaonbiddl.dbs.graphenedb.com:24787
    username: admin
    password: b.YEjBLMjEyqWB.yCtOOCklJIhgU9EE