kumuluzee:
  name: recomender-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://10.10.80.79:2379
configurations:
  neo4j:
    url: bolt://hobby-ghjnlebfkikggbkeaonbiddl.dbs.graphenedb.com:24787
    username: admin
    password: b.YEjBLMjEyqWB.yCtOOCklJIhgU9EE